/**
 * Mock data layer that simulates the Rust backend.
 * In production, all these helpers would call /api/* routes that proxy to the Rust backend.
 */
import type {
  Project,
  Deployment,
  Container,
  ServerInfo,
  ProcessInfo,
  DockerEvent,
  EnvVariable,
  ApiKey,
  Session,
  LogEntry,
  TimeSeries,
  User,
} from "./types";

export const mockUser: User = {
  id: "u_1",
  name: "Ahmed Hassan",
  email: "ahmed@railflow.io",
  avatarUrl: "https://i.pravatar.cc/150?img=12",
  role: "owner",
  twoFactorEnabled: true,
  createdAt: "2025-01-15T08:00:00Z",
};

const now = Date.now();
const minAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hourAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const dayAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

// ---------- Projects ----------
export const mockProjects: Project[] = [
  {
    id: "p_web",
    name: "Web Platform",
    slug: "web-platform",
    description: "Main marketing site & dashboard — Next.js + Tailwind",
    repo: "railflow/web-platform",
    repoUrl: "https://github.com/railflow/web-platform",
    branch: "main",
    runtime: "node",
    framework: "Next.js 16",
    domain: "railflow.io",
    customDomains: ["railflow.io", "www.railflow.io", "admin.railflow.io"],
    status: "done",
    health: "healthy",
    lastDeployAt: minAgo(14),
    lastDeployCommit: "a3f5c2e",
    lastDeployMessage: "feat: ship onboarding v2 with RTL support",
    autoDeploy: true,
    previewDeploy: true,
    buildCommand: "next build",
    installCommand: "bun install",
    startCommand: "next start",
    rootDir: "./",
    envCount: 24,
    secretCount: 8,
    stats: { totalDeploys: 412, successRate: 98.3, avgDeploySeconds: 87, last24hDeploys: 6 },
    resources: { cpuCores: 2, memoryMb: 2048, diskMb: 1024 },
    containerId: "c_web_1",
    imageUrl: "ghcr.io/railflow/web-platform:main",
    createdAt: dayAgo(245),
    updatedAt: minAgo(14),
    tags: ["production", "frontend", "critical"],
  },
  {
    id: "p_api",
    name: "API Gateway",
    slug: "api-gateway",
    description: "Rust-powered API gateway with JWT & rate limiting",
    repo: "railflow/api-gateway",
    repoUrl: "https://github.com/railflow/api-gateway",
    branch: "main",
    runtime: "rust",
    framework: "axum",
    domain: "api.railflow.io",
    customDomains: ["api.railflow.io"],
    status: "done",
    health: "healthy",
    lastDeployAt: hourAgo(3),
    lastDeployCommit: "b7e9d1f",
    lastDeployMessage: "perf: reduce p99 latency by 22% via connection pooling",
    autoDeploy: true,
    previewDeploy: false,
    buildCommand: "cargo build --release",
    installCommand: "cargo fetch",
    startCommand: "./api-gateway",
    rootDir: "./",
    envCount: 18,
    secretCount: 12,
    stats: { totalDeploys: 287, successRate: 99.6, avgDeploySeconds: 145, last24hDeploys: 2 },
    resources: { cpuCores: 4, memoryMb: 4096, diskMb: 512 },
    containerId: "c_api_1",
    imageUrl: "ghcr.io/railflow/api-gateway:main",
    createdAt: dayAgo(312),
    updatedAt: hourAgo(3),
    tags: ["production", "backend", "critical"],
  },
  {
    id: "p_worker",
    name: "Background Workers",
    slug: "workers",
    description: "Async job processors (queues, scheduled tasks, webhooks)",
    repo: "railflow/workers",
    repoUrl: "https://github.com/railflow/workers",
    branch: "main",
    runtime: "go",
    framework: "Go + Redis",
    domain: undefined,
    customDomains: [],
    status: "done",
    health: "healthy",
    lastDeployAt: hourAgo(11),
    lastDeployCommit: "c2a8f3b",
    lastDeployMessage: "fix: properly handle dead-letter queue retries",
    autoDeploy: true,
    previewDeploy: false,
    buildCommand: "go build -o worker ./cmd/worker",
    installCommand: "go mod download",
    startCommand: "./worker",
    rootDir: "./",
    envCount: 14,
    secretCount: 6,
    stats: { totalDeploys: 198, successRate: 97.5, avgDeploySeconds: 64, last24hDeploys: 3 },
    resources: { cpuCores: 1, memoryMb: 1024, diskMb: 256 },
    containerId: "c_worker_1",
    imageUrl: "ghcr.io/railflow/workers:main",
    createdAt: dayAgo(188),
    updatedAt: hourAgo(11),
    tags: ["production", "backend"],
  },
  {
    id: "p_ml",
    name: "ML Inference",
    slug: "ml-inference",
    description: "Real-time ML inference service — Python + ONNX",
    repo: "railflow/ml-inference",
    repoUrl: "https://github.com/railflow/ml-inference",
    branch: "main",
    runtime: "python",
    framework: "FastAPI + ONNX",
    domain: "infer.railflow.io",
    customDomains: ["infer.railflow.io"],
    status: "building",
    health: "degraded",
    lastDeployAt: minAgo(3),
    lastDeployCommit: "d9c1e2a",
    lastDeployMessage: "chore: upgrade onnxruntime to 1.20",
    autoDeploy: false,
    previewDeploy: true,
    buildCommand: "pip install -r requirements.txt",
    installCommand: "pip install -r requirements.txt",
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8000",
    rootDir: "./",
    envCount: 9,
    secretCount: 4,
    stats: { totalDeploys: 87, successRate: 94.2, avgDeploySeconds: 312, last24hDeploys: 4 },
    resources: { cpuCores: 8, memoryMb: 8192, diskMb: 4096 },
    containerId: "c_ml_1",
    imageUrl: "ghcr.io/railflow/ml-inference:main",
    createdAt: dayAgo(64),
    updatedAt: minAgo(3),
    tags: ["production", "ml", "gpu"],
  },
  {
    id: "p_docs",
    name: "Documentation",
    slug: "docs",
    description: "Static documentation site built with Astro",
    repo: "railflow/docs",
    repoUrl: "https://github.com/railflow/docs",
    branch: "main",
    runtime: "static",
    framework: "Astro",
    domain: "docs.railflow.io",
    customDomains: ["docs.railflow.io"],
    status: "done",
    health: "healthy",
    lastDeployAt: dayAgo(2),
    lastDeployCommit: "e5b2c4d",
    lastDeployMessage: "docs: add Rust backend architecture page",
    autoDeploy: true,
    previewDeploy: true,
    buildCommand: "astro build",
    installCommand: "npm install",
    startCommand: "npx serve dist",
    rootDir: "./",
    envCount: 4,
    secretCount: 1,
    stats: { totalDeploys: 156, successRate: 100, avgDeploySeconds: 42, last24hDeploys: 1 },
    resources: { cpuCores: 0.5, memoryMb: 512, diskMb: 256 },
    containerId: "c_docs_1",
    imageUrl: "ghcr.io/railflow/docs:main",
    createdAt: dayAgo(145),
    updatedAt: dayAgo(2),
    tags: ["production", "static"],
  },
  {
    id: "p_mobile",
    name: "Mobile API",
    slug: "mobile-api",
    description: "Backend for mobile apps — Node.js + tRPC + Prisma",
    repo: "railflow/mobile-api",
    repoUrl: "https://github.com/railflow/mobile-api",
    branch: "develop",
    runtime: "node",
    framework: "Node.js + tRPC",
    domain: "m.railflow.io",
    customDomains: ["m.railflow.io"],
    status: "failed",
    health: "unhealthy",
    lastDeployAt: hourAgo(8),
    lastDeployCommit: "f8a3d9e",
    lastDeployMessage: "wip: experimental push notifications — known broken",
    autoDeploy: false,
    previewDeploy: true,
    buildCommand: "tsc && node dist/main.js",
    installCommand: "npm ci",
    startCommand: "node dist/main.js",
    rootDir: "./",
    envCount: 16,
    secretCount: 7,
    stats: { totalDeploys: 233, successRate: 92.1, avgDeploySeconds: 76, last24hDeploys: 2 },
    resources: { cpuCores: 2, memoryMb: 2048, diskMb: 512 },
    containerId: undefined,
    imageUrl: "ghcr.io/railflow/mobile-api:develop",
    createdAt: dayAgo(98),
    updatedAt: hourAgo(8),
    tags: ["staging", "backend", "wip"],
  },
];

// ---------- Containers ----------
export const mockContainers: Container[] = [
  {
    id: "c_web_1",
    name: "web-platform-prod",
    image: "ghcr.io/railflow/web-platform:main",
    status: "running",
    health: "healthy",
    projectId: "p_web",
    projectName: "Web Platform",
    command: "next start -p 3000",
    created: dayAgo(14),
    uptime: 14 * 86400 + 3 * 3600,
    ports: [{ host: 3000, container: 3000, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 8.4,
      memoryUsedMb: 412,
      memoryLimitMb: 2048,
      netInMb: 156.3,
      netOutMb: 894.2,
      blockReadMb: 12.4,
      blockWriteMb: 6.1,
      pids: 87,
    },
    labels: { "railflow.project": "p_web", "railflow.env": "production" },
  },
  {
    id: "c_api_1",
    name: "api-gateway-prod",
    image: "ghcr.io/railflow/api-gateway:main",
    status: "running",
    health: "healthy",
    projectId: "p_api",
    projectName: "API Gateway",
    command: "./api-gateway --config /etc/railflow/config.toml",
    created: dayAgo(3),
    uptime: 3 * 86400 + 2 * 3600,
    ports: [{ host: 8080, container: 8080, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 23.7,
      memoryUsedMb: 287,
      memoryLimitMb: 4096,
      netInMb: 542.1,
      netOutMb: 678.9,
      blockReadMb: 4.2,
      blockWriteMb: 1.8,
      pids: 32,
    },
    labels: { "railflow.project": "p_api", "railflow.env": "production" },
  },
  {
    id: "c_worker_1",
    name: "workers-prod",
    image: "ghcr.io/railflow/workers:main",
    status: "running",
    health: "healthy",
    projectId: "p_worker",
    projectName: "Background Workers",
    command: "./worker",
    created: dayAgo(11),
    uptime: 11 * 86400 + 5 * 3600,
    ports: [],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 4.1,
      memoryUsedMb: 156,
      memoryLimitMb: 1024,
      netInMb: 28.7,
      netOutMb: 14.2,
      blockReadMb: 2.1,
      blockWriteMb: 9.4,
      pids: 14,
    },
    labels: { "railflow.project": "p_worker", "railflow.env": "production" },
  },
  {
    id: "c_ml_1",
    name: "ml-inference-prod",
    image: "ghcr.io/railflow/ml-inference:main",
    status: "running",
    health: "degraded",
    projectId: "p_ml",
    projectName: "ML Inference",
    command: "uvicorn app:app --host 0.0.0.0 --port 8000",
    created: hourAgo(2),
    uptime: 2 * 3600 + 14 * 60,
    ports: [{ host: 8000, container: 8000, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 67.2,
      memoryUsedMb: 5234,
      memoryLimitMb: 8192,
      netInMb: 89.4,
      netOutMb: 142.7,
      blockReadMb: 89.2,
      blockWriteMb: 12.8,
      pids: 124,
    },
    labels: { "railflow.project": "p_ml", "railflow.env": "production" },
  },
  {
    id: "c_docs_1",
    name: "docs-prod",
    image: "ghcr.io/railflow/docs:main",
    status: "running",
    health: "healthy",
    projectId: "p_docs",
    projectName: "Documentation",
    command: "npx serve dist -l 4000",
    created: dayAgo(2),
    uptime: 2 * 86400 + 7 * 3600,
    ports: [{ host: 4000, container: 4000, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 0.8,
      memoryUsedMb: 48,
      memoryLimitMb: 512,
      netInMb: 8.4,
      netOutMb: 23.6,
      blockReadMb: 0.4,
      blockWriteMb: 0.1,
      pids: 8,
    },
    labels: { "railflow.project": "p_docs", "railflow.env": "production" },
  },
  {
    id: "c_redis",
    name: "redis-cache",
    image: "redis:7.4-alpine",
    status: "running",
    health: "healthy",
    command: "redis-server --appendonly yes",
    created: dayAgo(45),
    uptime: 45 * 86400,
    ports: [{ host: 6379, container: 6379, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 1.2,
      memoryUsedMb: 89,
      memoryLimitMb: 256,
      netInMb: 4.7,
      netOutMb: 6.1,
      blockReadMb: 0.8,
      blockWriteMb: 12.4,
      pids: 5,
    },
    labels: { "railflow.managed": "true", "railflow.type": "database" },
  },
  {
    id: "c_pg",
    name: "postgres-prod",
    image: "postgres:17-alpine",
    status: "running",
    health: "healthy",
    command: "postgres -c shared_buffers=2GB",
    created: dayAgo(245),
    uptime: 245 * 86400,
    ports: [{ host: 5432, container: 5432, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 12.8,
      memoryUsedMb: 2156,
      memoryLimitMb: 4096,
      netInMb: 234.1,
      netOutMb: 189.7,
      blockReadMb: 156.3,
      blockWriteMb: 89.2,
      pids: 47,
    },
    labels: { "railflow.managed": "true", "railflow.type": "database" },
  },
  {
    id: "c_nginx",
    name: "edge-proxy",
    image: "nginx:1.27-alpine",
    status: "running",
    health: "healthy",
    command: "nginx -g 'daemon off;'",
    created: dayAgo(120),
    uptime: 120 * 86400,
    ports: [
      { host: 80, container: 80, protocol: "tcp" },
      { host: 443, container: 443, protocol: "tcp" },
    ],
    networks: ["railflow-edge"],
    stats: {
      cpuPercent: 3.4,
      memoryUsedMb: 78,
      memoryLimitMb: 512,
      netInMb: 1247.6,
      netOutMb: 1562.3,
      blockReadMb: 1.2,
      blockWriteMb: 4.8,
      pids: 11,
    },
    labels: { "railflow.managed": "true", "railflow.type": "proxy" },
  },
  {
    id: "c_old_mobile",
    name: "mobile-api-staging",
    image: "ghcr.io/railflow/mobile-api:develop",
    status: "stopped",
    health: "unknown",
    projectId: "p_mobile",
    projectName: "Mobile API",
    command: "node dist/main.js",
    created: dayAgo(8),
    uptime: 0,
    ports: [{ host: 3010, container: 3000, protocol: "tcp" }],
    networks: ["railflow-net"],
    stats: {
      cpuPercent: 0,
      memoryUsedMb: 0,
      memoryLimitMb: 2048,
      netInMb: 0,
      netOutMb: 0,
      blockReadMb: 0,
      blockWriteMb: 0,
      pids: 0,
    },
    labels: { "railflow.project": "p_mobile", "railflow.env": "staging" },
  },
];

// ---------- Deployments ----------
function makeStages(status: Deployment["status"], stages: Deployment["stages"] = []) {
  const baseStages: Deployment["stages"][number]["id"][] = ["queued", "cloning", "building", "pushing", "starting", "health", "done"];
  return baseStages.map((id, i) => {
    const existing = stages.find(s => s.id === id);
    if (existing) return existing;
    let s: "pending" | "running" | "success" | "failed" | "skipped" = "pending";
    if (status === "failed") {
      const failedAt = 3;
      if (i < failedAt) s = "success";
      else if (i === failedAt) s = "failed";
      else s = "skipped";
    } else if (status === "done") {
      s = "success";
    } else {
      const idx = baseStages.indexOf(status);
      if (i < idx) s = "success";
      else if (i === idx) s = "running";
    }
    return { id, status: s };
  });
}

export const mockDeployments: Deployment[] = [
  {
    id: "d_1",
    projectId: "p_ml",
    projectName: "ML Inference",
    status: "building",
    stage: "building",
    commitSha: "d9c1e2a",
    commitMessage: "chore: upgrade onnxruntime to 1.20",
    branch: "main",
    author: "Ahmed Hassan",
    authorAvatar: "https://i.pravatar.cc/40?img=12",
    environment: "production",
    triggeredBy: "manual",
    stages: makeStages("building"),
    startedAt: minAgo(3),
    url: "https://infer.railflow.io",
  },
  {
    id: "d_2",
    projectId: "p_web",
    projectName: "Web Platform",
    status: "done",
    stage: "done",
    commitSha: "a3f5c2e",
    commitMessage: "feat: ship onboarding v2 with RTL support",
    branch: "main",
    author: "Sara Mohamed",
    authorAvatar: "https://i.pravatar.cc/40?img=5",
    environment: "production",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: minAgo(14),
    finishedAt: minAgo(11),
    durationMs: 187_000,
    url: "https://railflow.io",
  },
  {
    id: "d_3",
    projectId: "p_api",
    projectName: "API Gateway",
    status: "done",
    stage: "done",
    commitSha: "b7e9d1f",
    commitMessage: "perf: reduce p99 latency by 22% via connection pooling",
    branch: "main",
    author: "Omar Khaled",
    authorAvatar: "https://i.pravatar.cc/40?img=8",
    environment: "production",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: hourAgo(3),
    finishedAt: hourAgo(3),
    durationMs: 145_000,
    url: "https://api.railflow.io",
  },
  {
    id: "d_4",
    projectId: "p_mobile",
    projectName: "Mobile API",
    status: "failed",
    stage: "building",
    commitSha: "f8a3d9e",
    commitMessage: "wip: experimental push notifications — known broken",
    branch: "develop",
    author: "Layla Ibrahim",
    authorAvatar: "https://i.pravatar.cc/40?img=20",
    environment: "staging",
    triggeredBy: "manual",
    stages: makeStages("failed"),
    startedAt: hourAgo(8),
    finishedAt: hourAgo(8),
    durationMs: 92_000,
    errorMessage: "Build failed: Cannot find module '@notifee/react-native' in src/push.ts:14:23",
  },
  {
    id: "d_5",
    projectId: "p_worker",
    projectName: "Background Workers",
    status: "done",
    stage: "done",
    commitSha: "c2a8f3b",
    commitMessage: "fix: properly handle dead-letter queue retries",
    branch: "main",
    author: "Yusuf Ali",
    authorAvatar: "https://i.pravatar.cc/40?img=15",
    environment: "production",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: hourAgo(11),
    finishedAt: hourAgo(11),
    durationMs: 64_000,
  },
  {
    id: "d_6",
    projectId: "p_web",
    projectName: "Web Platform",
    status: "done",
    stage: "done",
    commitSha: "9f2b1c8",
    commitMessage: "fix: dark mode toggle persists across reloads",
    branch: "main",
    author: "Sara Mohamed",
    authorAvatar: "https://i.pravatar.cc/40?img=5",
    environment: "production",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: hourAgo(20),
    finishedAt: hourAgo(20),
    durationMs: 178_000,
    url: "https://railflow.io",
  },
  {
    id: "d_7",
    projectId: "p_docs",
    projectName: "Documentation",
    status: "done",
    stage: "done",
    commitSha: "e5b2c4d",
    commitMessage: "docs: add Rust backend architecture page",
    branch: "main",
    author: "Ahmed Hassan",
    authorAvatar: "https://i.pravatar.cc/40?img=12",
    environment: "production",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: dayAgo(2),
    finishedAt: dayAgo(2),
    durationMs: 42_000,
    url: "https://docs.railflow.io",
  },
  {
    id: "d_8",
    projectId: "p_web",
    projectName: "Web Platform",
    status: "done",
    stage: "done",
    commitSha: "1a2b3c4",
    commitMessage: "feat: add bilingual i18n (ar/en) with RTL",
    branch: "main",
    author: "Sara Mohamed",
    authorAvatar: "https://i.pravatar.cc/40?img=5",
    environment: "preview",
    triggeredBy: "webhook",
    stages: makeStages("done"),
    startedAt: dayAgo(1),
    finishedAt: dayAgo(1),
    durationMs: 89_000,
    url: "https://preview-railflow-web.railflow.app",
  },
];

// ---------- Server Info ----------
export const mockServerInfo: ServerInfo = {
  hostname: "railflow-prod-01",
  os: "Ubuntu 24.04.2 LTS",
  kernel: "6.8.0-45-generic",
  uptime: 45 * 86400 + 7 * 3600 + 23 * 60,
  bootTime: dayAgo(45),
  cpu: {
    model: "AMD EPYC 9554P 64-Core Processor",
    cores: 16,
    physicalCores: 8,
    frequencyMhz: 3100,
    loadAvg1: 4.21,
    loadAvg5: 3.87,
    loadAvg15: 3.42,
    perCoreUsage: [42, 38, 67, 51, 23, 89, 31, 47, 58, 35, 71, 44, 29, 62, 56, 41],
    overallUsage: 46.9,
  },
  memory: {
    totalGb: 64,
    usedGb: 28.4,
    availableGb: 32.6,
    cachedGb: 3.0,
    swapTotalGb: 8,
    swapUsedGb: 0.2,
  },
  disk: {
    totalGb: 960,
    usedGb: 412,
    availableGb: 548,
    partitions: [
      { device: "/dev/nvme0n1p2", mount: "/", fsType: "ext4", totalGb: 200, usedGb: 87, usedPercent: 43.5 },
      { device: "/dev/nvme0n1p3", mount: "/var/lib/docker", fsType: "ext4", totalGb: 500, usedGb: 234, usedPercent: 46.8 },
      { device: "/dev/nvme0n1p4", mount: "/data", fsType: "ext4", totalGb: 200, usedGb: 78, usedPercent: 39.0 },
      { device: "/dev/sda1", mount: "/backups", fsType: "ext4", totalGb: 60, usedGb: 13, usedPercent: 21.7 },
    ],
  },
  network: {
    interfaces: [
      { name: "eth0", ip: "10.0.5.24", mac: "aa:bb:cc:dd:ee:01", inboundMbps: 423.7, outboundMbps: 612.4, totalInGb: 8924.5, totalOutGb: 12453.2, isUp: true },
      { name: "eth1", ip: "10.0.5.25", mac: "aa:bb:cc:dd:ee:02", inboundMbps: 0, outboundMbps: 0, totalInGb: 234.1, totalOutGb: 12.4, isUp: false },
      { name: "lo", ip: "127.0.0.1", mac: "00:00:00:00:00:00", inboundMbps: 12.4, outboundMbps: 12.4, totalInGb: 89.2, totalOutGb: 89.2, isUp: true },
    ],
  },
  docker: {
    version: "27.3.1",
    containersTotal: 12,
    containersRunning: 8,
    containersStopped: 4,
    images: 47,
    storageDriver: "overlay2",
  },
};

// ---------- Processes ----------
export const mockProcesses: ProcessInfo[] = [
  { pid: 1, name: "systemd", user: "root", cpuPercent: 0.0, memoryMb: 12.4, memoryPercent: 0.02, status: "S", startTime: dayAgo(45), command: "/sbin/init" },
  { pid: 1247, name: "dockerd", user: "root", cpuPercent: 4.2, memoryMb: 412.8, memoryPercent: 0.63, status: "S", startTime: dayAgo(45), command: "/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock" },
  { pid: 1289, name: "containerd", user: "root", cpuPercent: 1.8, memoryMb: 187.3, memoryPercent: 0.29, status: "S", startTime: dayAgo(45), command: "/usr/bin/containerd" },
  { pid: 4521, name: "nginx", user: "www-data", cpuPercent: 3.4, memoryMb: 78.4, memoryPercent: 0.12, status: "S", startTime: dayAgo(120), command: "nginx: master process /usr/sbin/nginx -g 'daemon off;'" },
  { pid: 8932, name: "api-gateway", user: "railflow", cpuPercent: 23.7, memoryMb: 287.4, memoryPercent: 0.44, status: "S", startTime: dayAgo(3), command: "./api-gateway --config /etc/railflow/config.toml" },
  { pid: 9012, name: "next-server", user: "railflow", cpuPercent: 8.4, memoryMb: 412.1, memoryPercent: 0.63, status: "S", startTime: dayAgo(14), command: "next-server (v16.1.3)" },
  { pid: 9234, name: "uvicorn", user: "railflow", cpuPercent: 67.2, memoryMb: 5234.8, memoryPercent: 7.99, status: "R", startTime: hourAgo(2), command: "uvicorn app:app --host 0.0.0.0 --port 8000" },
  { pid: 9456, name: "postgres", user: "postgres", cpuPercent: 12.8, memoryMb: 2156.3, memoryPercent: 3.29, status: "S", startTime: dayAgo(245), command: "postgres: 17/main: /usr/lib/postgresql/17/bin/postgres -D /var/lib/postgresql/17/main -c shared_buffers=2GB" },
  { pid: 9678, name: "redis-server", user: "redis", cpuPercent: 1.2, memoryMb: 89.4, memoryPercent: 0.14, status: "S", startTime: dayAgo(45), command: "redis-server *:6379" },
  { pid: 9876, name: "worker", user: "railflow", cpuPercent: 4.1, memoryMb: 156.2, memoryPercent: 0.24, status: "S", startTime: dayAgo(11), command: "./worker" },
  { pid: 10023, name: "node", user: "railflow", cpuPercent: 0.8, memoryMb: 48.2, memoryPercent: 0.07, status: "S", startTime: dayAgo(2), command: "npx serve dist -l 4000" },
  { pid: 10567, name: "cadvisor", user: "root", cpuPercent: 2.1, memoryMb: 134.7, memoryPercent: 0.21, status: "S", startTime: dayAgo(45), command: "/usr/bin/cadvisor --port=8081" },
  { pid: 10789, name: "prometheus", user: "prometheus", cpuPercent: 1.7, memoryMb: 287.5, memoryPercent: 0.44, status: "S", startTime: dayAgo(45), command: "/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml" },
  { pid: 10901, name: "grafana-server", user: "grafana", cpuPercent: 0.4, memoryMb: 198.3, memoryPercent: 0.30, status: "S", startTime: dayAgo(45), command: "/usr/sbin/grafana server --config=/etc/grafana/grafana.ini" },
  { pid: 11022, name: "sshd", user: "root", cpuPercent: 0.0, memoryMb: 8.4, memoryPercent: 0.01, status: "S", startTime: dayAgo(45), command: "/usr/sbin/sshd -D" },
];

// ---------- Docker Events ----------
export const mockDockerEvents: DockerEvent[] = [
  { id: "e_1", type: "container", action: "start", actor: { id: "c_ml_1", attributes: { name: "ml-inference-prod", image: "ghcr.io/railflow/ml-inference:main" } }, scope: "local", time: minAgo(2), message: "Container ml-inference-prod started" },
  { id: "e_2", type: "image", action: "pull", actor: { id: "sha256:d9c1e2a", attributes: { name: "ghcr.io/railflow/ml-inference:main" } }, scope: "local", time: minAgo(3), message: "Pulled image ghcr.io/railflow/ml-inference:main" },
  { id: "e_3", type: "container", action: "stop", actor: { id: "c_old_mobile", attributes: { name: "mobile-api-staging" } }, scope: "local", time: hourAgo(8), message: "Container mobile-api-staging stopped (exit code 1)" },
  { id: "e_4", type: "container", action: "health_status: unhealthy", actor: { id: "c_old_mobile", attributes: { name: "mobile-api-staging" } }, scope: "local", time: hourAgo(8), message: "Container mobile-api-staging became unhealthy" },
  { id: "e_5", type: "container", action: "start", actor: { id: "c_web_1", attributes: { name: "web-platform-prod" } }, scope: "local", time: minAgo(11), message: "Container web-platform-prod started" },
  { id: "e_6", type: "image", action: "pull", actor: { id: "sha256:a3f5c2e", attributes: { name: "ghcr.io/railflow/web-platform:main" } }, scope: "local", time: minAgo(13), message: "Pulled image ghcr.io/railflow/web-platform:main" },
  { id: "e_7", type: "container", action: "health_status: healthy", actor: { id: "c_web_1", attributes: { name: "web-platform-prod" } }, scope: "local", time: minAgo(10), message: "Container web-platform-prod became healthy" },
  { id: "e_8", type: "network", action: "connect", actor: { id: "railflow-net", attributes: { container: "c_ml_1" } }, scope: "local", time: minAgo(2), message: "Container c_ml_1 connected to network railflow-net" },
];

// ---------- Environment Variables (for Web Platform) ----------
export const mockEnvVariables: EnvVariable[] = [
  { id: "v_1", key: "NODE_ENV", value: "production", isSecret: false, isSensitive: false, createdAt: dayAgo(245), updatedAt: dayAgo(245) },
  { id: "v_2", key: "DATABASE_URL", value: "postgres://railflow:••••••••@postgres-prod:5432/railflow", isSecret: true, isSensitive: true, createdAt: dayAgo(245), updatedAt: dayAgo(45) },
  { id: "v_3", key: "REDIS_URL", value: "redis://redis-cache:6379/0", isSecret: false, isSensitive: false, createdAt: dayAgo(245), updatedAt: dayAgo(245) },
  { id: "v_4", key: "JWT_SECRET", value: "••••••••••••••••••••••••", isSecret: true, isSensitive: true, createdAt: dayAgo(245), updatedAt: dayAgo(30) },
  { id: "v_5", key: "GITHUB_CLIENT_ID", value: "Iv1.abc123def456", isSecret: false, isSensitive: false, createdAt: dayAgo(120), updatedAt: dayAgo(120) },
  { id: "v_6", key: "GITHUB_CLIENT_SECRET", value: "••••••••••••••••", isSecret: true, isSensitive: true, createdAt: dayAgo(120), updatedAt: dayAgo(120) },
  { id: "v_7", key: "STRIPE_SECRET_KEY", value: "sk_live_••••••••••••••••", isSecret: true, isSensitive: true, createdAt: dayAgo(89), updatedAt: dayAgo(89) },
  { id: "v_8", key: "SENTRY_DSN", value: "https://abc123@o789.ingest.sentry.io/123", isSecret: false, isSensitive: true, createdAt: dayAgo(60), updatedAt: dayAgo(60) },
  { id: "v_9", key: "LOG_LEVEL", value: "info", isSecret: false, isSensitive: false, createdAt: dayAgo(245), updatedAt: dayAgo(245) },
  { id: "v_10", key: "PORT", value: "3000", isSecret: false, isSensitive: false, createdAt: dayAgo(245), updatedAt: dayAgo(245) },
];

// ---------- API Keys ----------
export const mockApiKeys: ApiKey[] = [
  { id: "k_1", name: "CI/CD Pipeline", prefix: "rf_live_8K9p2X", scopes: ["deploy:create", "deploy:read", "project:read"], lastUsedAt: minAgo(14), createdAt: dayAgo(89) },
  { id: "k_2", name: "Monitoring (Grafana)", prefix: "rf_live_4M7n8Q", scopes: ["metrics:read", "logs:read"], lastUsedAt: minAgo(2), createdAt: dayAgo(120) },
  { id: "k_3", name: "Mobile App Backend", prefix: "rf_live_2R5t9L", scopes: ["project:read"], lastUsedAt: dayAgo(7), createdAt: dayAgo(45) },
  { id: "k_4", name: "Legacy Webhook (deprecated)", prefix: "rf_live_9B3k1Y", scopes: ["webhook:send"], lastUsedAt: dayAgo(124), createdAt: dayAgo(245), expiresAt: dayAgo(-30) },
];

// ---------- Sessions ----------
export const mockSessions: Session[] = [
  { id: "s_1", device: "MacBook Pro 16\"", browser: "Chrome 138", os: "macOS 15.2", ip: "156.21x.x.x", location: "Cairo, EG", current: true, lastActiveAt: minAgo(0), createdAt: hourAgo(2) },
  { id: "s_2", device: "iPhone 16 Pro", browser: "Safari Mobile", os: "iOS 18.2", ip: "156.21x.x.x", location: "Cairo, EG", current: false, lastActiveAt: hourAgo(6), createdAt: dayAgo(1) },
  { id: "s_3", device: "Linux Workstation", browser: "Firefox 132", os: "Ubuntu 24.04", ip: "10.0.x.x", location: "Cairo, EG", current: false, lastActiveAt: dayAgo(2), createdAt: dayAgo(7) },
  { id: "s_4", device: "iPad Air", browser: "Safari Mobile", os: "iPadOS 18.2", ip: "197.43.x.x", location: "Alexandria, EG", current: false, lastActiveAt: dayAgo(5), createdAt: dayAgo(14) },
];

// ---------- Logs ----------
const logMessages: Array<[LogEntry["level"], string]> = [
  ["info", "Server listening on port 3000"],
  ["info", "Worker connected to Redis at redis-cache:6379"],
  ["success", "Health check passed (status=200, ms=42)"],
  ["info", "POST /api/v1/deployments 201 87ms"],
  ["info", "GET /api/v1/projects 200 12ms"],
  ["warn", "Rate limit threshold reached for IP 197.43.x.x (1000 req/min)"],
  ["info", "WebSocket connection established (client=c_8x2a)"],
  ["success", "Build completed in 87s (size: 4.2MB)"],
  ["info", "Image pushed to ghcr.io/railflow/web-platform:main"],
  ["error", "Failed to connect to stripe API (timeout after 5000ms) — retrying in 3s"],
  ["info", "Stripe API retry succeeded (attempt 2)"],
  ["debug", "Cache hit for key user:42:profile"],
  ["success", "Deployment d_2 marked as live"],
  ["info", "Container c_web_1 health status: healthy"],
  ["warn", "Memory usage at 78% on container c_ml_1"],
  ["info", "GET /api/v1/containers 200 28ms"],
  ["error", "Build failed: Cannot find module '@notifee/react-native'"],
  ["info", "Pulling image ghcr.io/railflow/ml-inference:main (1.2GB)"],
  ["success", "Image pulled successfully"],
  ["info", "Starting container ml-inference-prod"],
];

export function generateLogs(count: number = 50): LogEntry[] {
  const out: LogEntry[] = [];
  for (let i = 0; i < count; i++) {
    const [level, msg] = logMessages[Math.floor(Math.random() * logMessages.length)];
    out.push({
      id: `log_${i}_${Math.random().toString(36).slice(2, 8)}`,
      timestamp: new Date(now - i * (5_000 + Math.random() * 15_000)).toISOString(),
      level,
      source: ["api", "worker", "web", "docker", "scheduler"][Math.floor(Math.random() * 5)],
      message: msg,
    });
  }
  return out;
}

// ---------- Time Series ----------
export function generateTimeSeries(
  points: number = 60,
  base: number = 50,
  variance: number = 20,
  intervalMs: number = 60_000,
  unit: string = "%"
): TimeSeries {
  const pts = Array.from({ length: points }, (_, i) => ({
    timestamp: new Date(now - (points - i) * intervalMs).toISOString(),
    value: Math.max(0, Math.min(100, base + (Math.random() - 0.5) * variance * 2 + Math.sin(i / 8) * 5)),
  }));
  return { name: "default", points: pts, unit };
}

export function generateMultiSeries(): {
  cpu: TimeSeries;
  memory: TimeSeries;
  network: TimeSeries;
  deployments: TimeSeries;
} {
  return {
    cpu: { ...generateTimeSeries(60, 46, 18), name: "CPU", color: "oklch(0.72 0.22 295)" },
    memory: { ...generateTimeSeries(60, 44, 12), name: "Memory", color: "oklch(0.78 0.17 190)" },
    network: { ...generateTimeSeries(60, 30, 25), name: "Network", color: "oklch(0.75 0.2 145)" },
    deployments: {
      name: "Deployments",
      unit: "count",
      color: "oklch(0.78 0.18 75)",
      points: Array.from({ length: 24 }, (_, i) => ({
        timestamp: new Date(now - (24 - i) * 3_600_000).toISOString(),
        value: Math.floor(Math.random() * 5) + 1,
      })),
    },
  };
}
